import polars as pl

In [2]:
data = {
    'name' : ['Talha', 'Maheen', 'Zaviyar', 'Huzaifa', 'Abdullah'],
    'age' : [17, 14, 2, 8, 7],
    'weight' : [82.9, 62.5, 20.6, 33.1, 30.3],  # (kg)
    'height' : [1.56, 1.77, 1.1, 1.75, 1.56],  # (m)
}

In [3]:
df = pl.DataFrame(
    data=data
)

In [9]:
df.head()

shape: (5, 4)
┌──────────┬─────┬────────┬────────┐
│ name     ┆ age ┆ weight ┆ height │
│ ---      ┆ --- ┆ ---    ┆ ---    │
│ str      ┆ i64 ┆ f64    ┆ f64    │
╞══════════╪═════╪════════╪════════╡
│ Talha    ┆ 17  ┆ 82.9   ┆ 1.56   │
│ Maheen   ┆ 14  ┆ 62.5   ┆ 1.77   │
│ Zaviyar  ┆ 2   ┆ 20.6   ┆ 1.1    │
│ Huzaifa  ┆ 8   ┆ 33.1   ┆ 1.75   │
│ Abdullah ┆ 7   ┆ 30.3   ┆ 1.56   │
└──────────┴─────┴────────┴────────┘

In [16]:
df.write_csv('Datasets/demo-dataframe.csv')

In [18]:
df = pl.read_csv('Datasets/demo-dataframe.csv')

In [19]:
df.head()

shape: (5, 4)
┌──────────┬─────┬────────┬────────┐
│ name     ┆ age ┆ weight ┆ height │
│ ---      ┆ --- ┆ ---    ┆ ---    │
│ str      ┆ i64 ┆ f64    ┆ f64    │
╞══════════╪═════╪════════╪════════╡
│ Talha    ┆ 17  ┆ 82.9   ┆ 1.56   │
│ Maheen   ┆ 14  ┆ 62.5   ┆ 1.77   │
│ Zaviyar  ┆ 2   ┆ 20.6   ┆ 1.1    │
│ Huzaifa  ┆ 8   ┆ 33.1   ┆ 1.75   │
│ Abdullah ┆ 7   ┆ 30.3   ┆ 1.56   │
└──────────┴─────┴────────┴────────┘

In [25]:
df.columns

['name', 'age', 'weight', 'height']